// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI7yWS_JPmdlw0HZ6cCMig9QbA_mTK1mo',
    appId: '1:325043443483:web:ea762c49792950bbd625be',
    messagingSenderId: '325043443483',
    projectId: 'no-dues-cfe51',
    authDomain: 'no-dues-cfe51.firebaseapp.com',
    storageBucket: 'no-dues-cfe51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3EHCeGXrhdTWBI8fCTe72BaFNoLOu5Ss',
    appId: '1:325043443483:android:5ab7e94d7efad8b1d625be',
    messagingSenderId: '325043443483',
    projectId: 'no-dues-cfe51',
    storageBucket: 'no-dues-cfe51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39hNUtWWfSXU6-3aFD5rhrWplOfnqZ5c',
    appId: '1:325043443483:ios:36680601d39b3bbfd625be',
    messagingSenderId: '325043443483',
    projectId: 'no-dues-cfe51',
    storageBucket: 'no-dues-cfe51.appspot.com',
    iosBundleId: 'com.example.noDues',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA39hNUtWWfSXU6-3aFD5rhrWplOfnqZ5c',
    appId: '1:325043443483:ios:36680601d39b3bbfd625be',
    messagingSenderId: '325043443483',
    projectId: 'no-dues-cfe51',
    storageBucket: 'no-dues-cfe51.appspot.com',
    iosBundleId: 'com.example.noDues',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI7yWS_JPmdlw0HZ6cCMig9QbA_mTK1mo',
    appId: '1:325043443483:web:1d6bf6df829f9984d625be',
    messagingSenderId: '325043443483',
    projectId: 'no-dues-cfe51',
    authDomain: 'no-dues-cfe51.firebaseapp.com',
    storageBucket: 'no-dues-cfe51.appspot.com',
  );
}
